<script setup lang="ts">
import { onMounted, ref } from 'vue'
type User = { id: string; account: string; displayName: string; role: string; orgId: string; departmentId: string; enabled: boolean }
const props = defineProps<{ api: string; role: string }>()
const users = ref<User[]>([]); const selected = ref<User | null>(null); const loading = ref(false); const saving = ref(false); const message = ref(''); const password = ref('')
const headers = () => ({ 'Content-Type': 'application/json', 'X-Role': props.role })
async function request<T>(path: string, options: RequestInit = {}) { const response = await fetch(`${props.api}${path}`, { ...options, credentials: 'include', headers: { ...headers(), ...(options.headers || {}) } }); if (!response.ok) throw new Error((await response.text()) || '请求失败'); return response.json() as Promise<T> }
async function load() { loading.value = true; try { users.value = await request<User[]>('/api/admin/users'); if (!selected.value) selected.value = users.value[0] || null } catch (e) { message.value = (e as Error).message } finally { loading.value = false } }
async function save() { if (!selected.value) return; saving.value = true; message.value = ''; try { selected.value = await request<User>(`/api/admin/users/${selected.value.id}`, { method: 'PUT', body: JSON.stringify(selected.value) }); await load(); message.value = '用户配置已保存并记录审计' } catch (e) { message.value = (e as Error).message } finally { saving.value = false } }
async function resetPassword() { if (!selected.value || !password.value) { message.value = '请输入新密码'; return }; saving.value = true; try { await request(`/api/admin/users/${selected.value.id}/reset-password`, { method: 'POST', body: JSON.stringify({ password: password.value }) }); password.value = ''; message.value = '密码已重置并记录审计' } catch (e) { message.value = (e as Error).message } finally { saving.value = false } }
onMounted(load)
</script>
<template>
  <section class="admin-user-workspace page-section"><div class="page-header"><div><p class="eyebrow">系统管理 / 账号与权限</p><h1>账号与角色</h1><p class="page-desc">集中维护企业账号、角色权限和组织归属，账号变更会进入系统审计。</p></div><span class="formal-source-label">LOCAL DIRECTORY</span></div><div v-if="message" class="fulfillment-error">{{ message }}<button @click="message=''">关闭</button></div><div class="admin-user-layout"><section class="panel admin-user-table"><div class="section-heading"><div><h2>用户目录</h2><p class="section-caption">共 {{ users.length }} 个账号，不开放公开注册</p></div></div><div v-if="loading" class="inline-empty">正在加载用户目录...</div><button v-for="user in users" :key="user.id" class="admin-user-row" :class="{ active: selected?.id === user.id }" @click="selected = user"><span class="role-mark">{{ user.displayName.slice(0, 1) }}</span><span><b>{{ user.displayName }}</b><small>{{ user.account }} · {{ user.id }}</small></span><i :class="['status-tag', { disabled: !user.enabled }]">{{ user.enabled ? '启用' : '停用' }}</i><strong>{{ user.role }}</strong></button></section><section v-if="selected" class="panel admin-user-editor"><div class="section-heading"><div><p class="eyebrow">USER PROFILE</p><h2>{{ selected.displayName }}</h2><p class="section-caption">账号：{{ selected.account }} · ID：{{ selected.id }}</p></div><button class="primary-action" :disabled="saving" @click="save">{{ saving ? '保存中...' : '保存配置' }}</button></div><div class="form-grid admin-form-grid"><label>显示名称<input v-model="selected.displayName" /></label><label>角色<select v-model="selected.role"><option>ADMIN</option><option>LEGAL</option><option>BUSINESS</option><option>VIEWER</option></select></label><label>组织 ID<input v-model="selected.orgId" /></label><label>部门 ID<input v-model="selected.departmentId" /></label><label class="admin-switch"><input v-model="selected.enabled" type="checkbox" /><span><b>账号启用</b><small>停用后无法登录</small></span></label></div><div class="admin-password"><div><h3>密码重置</h3><p>仅管理员可操作，重置后立即生效。</p></div><input v-model="password" type="password" placeholder="输入至少 6 位新密码" /><button class="secondary-action" :disabled="saving" @click="resetPassword">重置密码</button></div></section></div></section>
</template>
