<script setup lang="ts">
import { onMounted, ref } from 'vue'

type Change = { id: number; changeNo: string; changeType: number; changeTitle: string; changeReason: string; beforeContentVersionId: number; afterContentVersionId: number; effectiveContentVersionId: number | null; signDate: string | null; effectDate: string | null; approvalStatus: number; approvalNo: string | null }
const props = defineProps<{ api: string; role: string; contractId: number }>()
const rows = ref<Change[]>([]); const loading = ref(false); const error = ref('')
const form = ref({ changeType: 1, changeTitle: '', changeReason: '', content: '' })
const selected = ref<Change | null>(null); const signDate = ref(''); const effectDate = ref('')
const headers = () => ({ 'Content-Type': 'application/json', 'X-Role': props.role })
async function request<T>(path: string, options: RequestInit = {}): Promise<T> { const response = await fetch(`${props.api}${path}`, { ...options, headers: { ...headers(), ...(options.headers || {}) } }); if (!response.ok) throw new Error((await response.text()) || '请求失败'); return response.json() }
async function load() { loading.value = true; try { rows.value = await request<Change[]>(`/api/contracts/${props.contractId}/changes`) } catch (e) { error.value = (e as Error).message } finally { loading.value = false } }
async function create() { if (!form.value.changeTitle || !form.value.content) { error.value = '请填写变更标题和变更后正文'; return }; try { await request(`/api/contracts/${props.contractId}/changes`, { method: 'POST', body: JSON.stringify(form.value) }); form.value = { changeType: 1, changeTitle: '', changeReason: '', content: '' }; await load() } catch (e) { error.value = (e as Error).message } }
async function action(id: number, name: string) { try { selected.value = await request<Change>(`/api/contracts/${props.contractId}/changes/${id}/${name}`, { method: 'POST' }); await load() } catch (e) { error.value = (e as Error).message } }
async function effective() { if (!selected.value || !signDate.value || !effectDate.value) { error.value = '请填写变更签署日期和生效日期'; return }; try { await request(`/api/contracts/${props.contractId}/changes/${selected.value.id}/effective?signDate=${signDate.value}&effectDate=${effectDate.value}`, { method: 'POST' }); await load(); selected.value = null } catch (e) { error.value = (e as Error).message } }
function typeName(type: number) { return ({ 1: '补充协议', 2: '内容变更', 3: '合同解除', 4: '合同终止' } as Record<number, string>)[type] || '其他' }
function approvalName(status: number) { return ({ 0: '未提交', 1: '审批中', 2: '已通过', 3: '已驳回', 4: '已撤回' } as Record<number, string>)[status] || '未知' }
onMounted(load)
</script>

<template>
  <section class="change-workspace page-section"><div class="page-header"><div><button class="back-button" @click="$emit('back')">← 返回合同详情</button><p class="eyebrow">合同详情 / 变更管理</p><h1>变更与补充协议</h1><p class="page-desc">变更独立审批，审批生效后才更新合同当前正文版本。</p></div></div><div v-if="error" class="fulfillment-error">{{ error }}<button @click="error=''">关闭</button></div><div class="change-layout"><section class="panel change-create"><div class="section-heading"><div><h2>发起变更</h2><p class="section-caption">变更前版本会被保留，审批前不更新当前生效正文。</p></div></div><div class="form-grid"><label>变更类型<select v-model.number="form.changeType"><option v-for="item in [1,2,3,4]" :key="item" :value="item">{{ typeName(item) }}</option></select></label><label>变更标题<input v-model="form.changeTitle" placeholder="例如：补充付款节点" /></label><label class="full-width">变更原因<textarea v-model="form.changeReason" rows="3" placeholder="填写变更原因和业务背景" /></label><label class="full-width">变更后正文<textarea v-model="form.content" rows="9" placeholder="填写变更后的完整合同正文" /></label></div><div class="form-footer"><span class="muted">将生成新的正文版本并关联本次变更</span><button class="primary-action" @click="create">保存变更草稿</button></div></section><section class="panel change-list"><div class="section-heading"><div><h2>变更记录</h2><p class="section-caption">共 {{ rows.length }} 条记录</p></div></div><div v-if="loading" class="inline-empty">正在加载...</div><div v-else-if="!rows.length" class="empty-state"><strong>暂无变更记录</strong><span>合同发生内容调整时，从左侧发起变更。</span></div><div v-else class="version-list"><div v-for="item in rows" :key="item.id" class="change-row"><span><b>{{ item.changeTitle }}</b><small>{{ item.changeNo }} · {{ typeName(item.changeType) }} · 前版本 v{{ item.beforeContentVersionId }} / 后版本 v{{ item.afterContentVersionId }}</small></span><span class="change-actions"><i class="status-tag">{{ approvalName(item.approvalStatus) }}</i><button v-if="item.approvalStatus === 0" class="link-button" @click="action(item.id, 'submit')">提交审批</button><button v-if="item.approvalStatus === 1" class="link-button" @click="action(item.id, 'mock-approve')">模拟通过</button><button v-if="item.approvalStatus === 2 && !item.effectiveContentVersionId" class="link-button" @click="selected=item">确认生效</button></span></div></div></section></div><section v-if="selected" class="panel effective-panel"><div><h2>确认变更生效</h2><p class="section-caption">审批通过后填写签署和生效日期，生效后更新当前正文版本。</p></div><label>签署日期<input v-model="signDate" type="date" /></label><label>生效日期<input v-model="effectDate" type="date" /></label><button class="primary-action" @click="effective">确认生效</button></section></section>
  <section v-if="rows.some(item => item.approvalStatus === 1)" class="panel change-list"><div class="section-heading"><div><h2>审批处理中</h2><p class="section-caption">可模拟通过、驳回或撤回当前变更。</p></div></div><div class="version-list"><div v-for="item in rows.filter(item => item.approvalStatus === 1)" :key="`approval-${item.id}`" class="change-row"><span><b>{{ item.changeTitle }}</b><small>{{ item.changeNo }} · {{ approvalName(item.approvalStatus) }}</small></span><span class="change-actions"><button class="link-button" @click="action(item.id, 'mock-approve')">模拟通过</button><button class="link-button" @click="action(item.id, 'reject')">模拟驳回</button><button class="link-button" @click="action(item.id, 'withdraw')">撤回</button></span></div></div></section>
</template>
