<script setup lang="ts">
import { computed, ref, watch } from 'vue'
type Contract = { id: number; contractNo: string; name: string; typeName: string; partyName: string; status: string; updatedAt: string; totalAmount?: number | null; currency?: string | null; expireDate?: string | null }
type Type = { id: number; name: string; subtype: string; category: string; enabled: boolean }
const props = defineProps<{ contracts: Contract[]; types: Type[]; canCreate: boolean; initialStatus?: string }>()
const emit = defineEmits<{ open: [id: number]; create: [] }>()
const keyword = ref(''); const typeId = ref('ALL'); const status = ref('ALL'); const party = ref('ALL')
const statuses = ['ALL', '草稿', '待签署', '履行中', '已完成', '已终止', '已作废']
const filtered = computed(() => props.contracts.filter(item => { const q = keyword.value.trim().toLowerCase(); const type = props.types.find(t => t.name === item.typeName); return (!q || [item.name, item.contractNo, item.typeName, item.partyName].some(v => v.toLowerCase().includes(q))) && (typeId.value === 'ALL' || String(type?.id) === typeId.value) && (status.value === 'ALL' || item.status === status.value) && (party.value === 'ALL' || item.partyName === party.value) }))
const parties = computed(() => [...new Set(props.contracts.map(item => item.partyName).filter(Boolean))])
function reset() { keyword.value = ''; typeId.value = 'ALL'; status.value = 'ALL'; party.value = 'ALL' }
function exportRows() { const escape = (v: string) => `"${v.replace(/"/g, '""')}"`; const csv = ['合同编号,合同名称,合同类型,对方主体,金额,到期日期,状态', ...filtered.value.map(item => [item.contractNo, item.name, item.typeName, item.partyName, String(item.totalAmount ?? ''), item.expireDate || '', item.status].map(escape).join(','))].join('\n'); const url = URL.createObjectURL(new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = `合同台账-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url) }
watch(() => props.initialStatus, value => { if (value && statuses.includes(value)) status.value = value }, { immediate: true })
</script>
<template>
  <section class="ledger-workspace page-section">
    <div class="page-header"><div><p class="eyebrow">合同中心 / 合同台账</p><h1>合同台账</h1><p class="page-desc">按合同编号、类型、对方主体和状态查找合同。点击整行进入详情，不在台账中做批量编辑。</p></div><div class="header-actions"><span class="sync-note">当前可见 {{ props.contracts.length }} 份合同</span><button v-if="canCreate" class="primary-action" @click="emit('create')">＋ 新建合同</button></div></div>
    <section class="panel ledger-filter-panel"><div class="ledger-filter-main"><label class="search-box"><span>⌕</span><input v-model="keyword" placeholder="搜索合同编号、名称、类型或对方主体"></label><label class="filter-field"><span>合同类型</span><select v-model="typeId"><option value="ALL">全部类型</option><option v-for="type in props.types.filter(item => item.enabled)" :key="type.id" :value="String(type.id)">{{ type.name }} · {{ type.subtype }}</option></select></label><label class="filter-field"><span>合同状态</span><select v-model="status"><option v-for="item in statuses" :key="item" :value="item">{{ item === 'ALL' ? '全部状态' : item }}</option></select></label><label class="filter-field"><span>对方主体</span><select v-model="party"><option value="ALL">全部主体</option><option v-for="item in parties" :key="item">{{ item }}</option></select></label><button class="ghost-button" @click="reset">重置</button></div><div class="ledger-filter-meta"><span>筛选结果 <b>{{ filtered.length }}</b> 份</span><button class="secondary-action" :disabled="!filtered.length" @click="exportRows">导出当前结果</button></div></section>
    <section class="panel ledger-table-panel"><div class="ledger-table-toolbar"><div><h2>合同列表</h2><span>字段按业务核对顺序排列：合同信息、主体、分类、期限、金额和状态。</span></div></div><div class="ledger-table-scroll"><div class="ledger-table-head"><span>合同信息</span><span>对方主体</span><span>合同类型</span><span>金额 / 币种</span><span>合同期限</span><span>经办与更新</span><span>状态</span></div><button v-for="item in filtered" :key="item.id" class="ledger-table-row" @click="emit('open', item.id)"><span class="ledger-contract-info"><b>{{ item.name }}</b><small>{{ item.contractNo }}</small></span><span>{{ item.partyName }}</span><span><b>{{ item.typeName }}</b><small>{{ props.types.find(type => type.name === item.typeName)?.category || '未分类' }}</small></span><span>{{ item.totalAmount == null ? '未设置' : item.totalAmount.toLocaleString('zh-CN') }} <small>{{ item.currency || 'CNY' }}</small></span><span>{{ item.expireDate || '未设置' }}</span><span><small>经办信息待配置</small><small>{{ item.updatedAt ? new Date(item.updatedAt).toLocaleDateString('zh-CN') : '未更新' }}</small></span><span><i class="status-tag">{{ item.status }}</i></span></button><div v-if="!filtered.length" class="empty-state"><strong>没有符合条件的合同</strong><span>调整筛选条件，或从右上角新建合同。</span><button class="link-button" @click="reset">清除筛选</button></div></div></section>
  </section>
</template>
