<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
type Role = { code: string; name: string; description: string; permissions: string[]; dataScope: string; typeIds: number[]; sensitiveFieldAccess: boolean }
type Audit = { id: number; module: string; action: string; result: string; operator: string; description: string; operatedAt: string }
type ContractType = { id: number; name: string; subtype: string }
const props = defineProps<{ api: string; role: string; types: ContractType[] }>()
const roles = ref<Role[]>([]); const selectedCode = ref(''); const audit = ref<Audit[]>([]); const loading = ref(false); const saving = ref(false); const error = ref(''); const auditModule = ref('ALL'); const keyword = ref('')
const permissions = [{ code: 'VIEW', label: '查看合同' }, { code: 'EDIT', label: '新建与编辑' }, { code: 'APPROVE', label: '审批与审查' }, { code: 'FULFILL', label: '履行与收付款' }, { code: 'TEMPLATE', label: '系统配置' }, { code: 'EXPORT', label: '导出下载' }, { code: 'SENSITIVE', label: '敏感字段' }]
const scopes = [{ code: 'ALL', label: '全部数据' }, { code: 'ORGANIZATION', label: '所属组织' }, { code: 'DEPARTMENT', label: '所属部门' }, { code: 'SELF_AND_PARTICIPANTS', label: '本人及参与合同' }, { code: 'NAMED_CONTRACTS', label: '指定合同范围' }]
const selected = computed(() => roles.value.find(item => item.code === selectedCode.value) || null)
const headers = () => ({ 'Content-Type': 'application/json', 'X-Role': props.role })
async function request<T>(path: string, options: RequestInit = {}) { const response = await fetch(`${props.api}${path}`, { ...options, headers: { ...headers(), ...(options.headers || {}) } }); if (!response.ok) throw new Error((await response.text()) || '请求失败'); return response.json() as Promise<T> }
async function loadRoles() { roles.value = await request<Role[]>('/api/permission-roles'); if (!selectedCode.value) selectedCode.value = roles.value[0]?.code || '' }
async function loadAudit() { const params = new URLSearchParams(); if (auditModule.value !== 'ALL') params.set('module', auditModule.value); if (keyword.value.trim()) params.set('keyword', keyword.value.trim()); audit.value = await request<Audit[]>(`/api/audit-logs?${params}`) }
async function load() { loading.value = true; try { await Promise.all([loadRoles(), loadAudit()]) } catch (e) { error.value = (e as Error).message } finally { loading.value = false } }
function togglePermission(code: string) { if (!selected.value) return; selected.value.permissions = selected.value.permissions.includes(code) ? selected.value.permissions.filter(item => item !== code) : [...selected.value.permissions, code] }
function toggleType(id: number) { if (!selected.value) return; selected.value.typeIds = selected.value.typeIds.includes(id) ? selected.value.typeIds.filter(item => item !== id) : [...selected.value.typeIds, id] }
async function save() { if (!selected.value) return; saving.value = true; try { await request(`/api/permission-roles/${selected.value.code}`, { method: 'PUT', body: JSON.stringify({ permissions: selected.value.permissions, dataScope: selected.value.dataScope, typeIds: selected.value.typeIds, sensitiveFieldAccess: selected.value.sensitiveFieldAccess }) }); await load() } catch (e) { error.value = (e as Error).message } finally { saving.value = false } }
onMounted(load)
</script>

<template>
  <section class="permission-workspace page-section"><div class="page-header"><div><p class="eyebrow">系统管理 / 权限与审计</p><h1>权限与审计</h1><p class="page-desc">按角色、数据范围、合同类型和敏感字段控制访问；所有配置调整和合同操作可追溯。</p></div></div><div v-if="error" class="fulfillment-error">{{ error }}<button @click="error=''">关闭</button></div>
    <div class="permission-layout"><aside class="panel permission-role-list"><div class="section-heading"><div><h2>角色</h2><p class="section-caption">第一阶段使用内置组织与人员</p></div></div><div v-if="loading" class="inline-empty">正在加载...</div><button v-for="item in roles" :key="item.code" :class="['permission-role-row', { active: item.code === selectedCode }]" @click="selectedCode=item.code"><span class="role-mark">{{ item.name.slice(0, 1) }}</span><span><b>{{ item.name }}</b><small>{{ item.description }}</small></span></button></aside>
      <section v-if="selected" class="panel permission-detail"><div class="permission-detail-head"><div><p class="eyebrow">角色权限</p><h2>{{ selected.name }}</h2><span>{{ selected.description }}</span></div><button class="primary-action" :disabled="saving" @click="save">{{ saving ? '保存中...' : '保存权限' }}</button></div><div class="permission-section"><h3>页面与动作权限</h3><div class="permission-checks"><label v-for="item in permissions" :key="item.code"><input type="checkbox" :checked="selected.permissions.includes(item.code)" @change="togglePermission(item.code)" /><span>{{ item.label }}</span></label></div></div><div class="permission-section split"><div><h3>默认数据范围</h3><select v-model="selected.dataScope"><option v-for="item in scopes" :key="item.code" :value="item.code">{{ item.label }}</option></select><p class="section-caption">数据范围与合同类型权限取交集；指定合同作为受控例外。</p></div><label class="sensitive-switch"><input v-model="selected.sensitiveFieldAccess" type="checkbox" /><span><b>敏感字段访问</b><small>薪酬、身份证号、借款及担保等字段</small></span></label></div><div class="permission-section"><div class="section-heading"><div><h3>合同类型权限</h3><p class="section-caption">合同类型是实际授权单位，大类只用于页面分组。</p></div></div><div class="type-checks"><label v-for="item in props.types" :key="item.id"><input type="checkbox" :checked="selected.typeIds.includes(item.id)" @change="toggleType(item.id)" /><span>{{ item.name }} · {{ item.subtype }}</span></label></div></div></section></div>
    <section class="panel audit-panel"><div class="section-heading"><div><h2>全局审计记录</h2><p class="section-caption">合同操作、权限配置及后续文件、审批、AI、导出操作统一追溯。</p></div><div class="audit-filters"><select v-model="auditModule" @change="loadAudit"><option value="ALL">全部模块</option><option value="合同">合同</option><option value="权限与审计">权限与审计</option></select><input v-model="keyword" placeholder="搜索操作、人员或说明" @keyup.enter="loadAudit" /><button class="secondary-action" @click="loadAudit">查询</button></div></div><div class="audit-table"><div class="audit-head"><span>模块</span><span>操作</span><span>结果</span><span>操作人</span><span>说明</span><span>时间</span></div><div v-for="item in audit" :key="item.id" class="audit-row"><span>{{ item.module }}</span><b>{{ item.action }}</b><i :class="['status-tag', { failed: item.result !== 'SUCCESS' }]">{{ item.result === 'SUCCESS' ? '成功' : '失败' }}</i><span>{{ item.operator }}</span><span>{{ item.description }}</span><time>{{ new Date(item.operatedAt).toLocaleString('zh-CN') }}</time></div><div v-if="!audit.length" class="inline-empty">暂无匹配的审计记录</div></div></section>
  </section>
</template>
