package com.hrcontract.application;

import com.fasterxml.jackson.databind.JsonNode;
import com.hrcontract.integration.IamClient;
import com.hrcontract.integration.IamProperties;
import jakarta.servlet.http.HttpSession;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.http.HttpStatus;
import java.util.Map;
import java.util.UUID;

@Service
public class AuthenticationService {
    private final LocalAuthService local; private final IamClient iam; private final IamProperties properties;
    public AuthenticationService(LocalAuthService local, IamClient iam, IamProperties properties){this.local=local;this.iam=iam;this.properties=properties;}
    public Map<String,Object> login(String account,String password,HttpSession session){ if(!properties.iam()) return local.login(account,password,session); if(!properties.configured()) throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"IAM 尚未配置，请联系平台管理员"); JsonNode root=iam.passwordLogin(account,password,"ContractSystem@Browser"); return establish(root,session,account); }
    public String beginOidc(HttpSession session, String returnTo){ if(!properties.iam()||!properties.oidcConfigured()) throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"OIDC 尚未配置"); String state=UUID.randomUUID().toString(); session.setAttribute("oidc_state",state); session.setAttribute("oidc_return_to", safeReturnTo(returnTo)); return iam.authorizationUrl(state,null); }
    public String callback(String code,String state,HttpSession session){ Object expected=session.getAttribute("oidc_state"); if(expected==null||!expected.toString().equals(state)) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"OIDC state 校验失败"); session.removeAttribute("oidc_state"); String returnTo=String.valueOf(session.getAttribute("oidc_return_to")); session.removeAttribute("oidc_return_to"); JsonNode token=iam.exchangeCode(code,null); JsonNode data=token.path("data").isObject()?token.path("data"):token; String accessToken=data.path("accessToken").asText(data.path("access_token").asText("")); if(accessToken.isBlank()) throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"OIDC 未返回 access token"); JsonNode user=iam.userInfo(accessToken); if(user.isObject()) { ((com.fasterxml.jackson.databind.node.ObjectNode) user).set("accessToken",com.fasterxml.jackson.databind.node.TextNode.valueOf(accessToken)); if(data.has("refreshToken")) ((com.fasterxml.jackson.databind.node.ObjectNode) user).set("refreshToken",data.get("refreshToken")); if(data.has("refresh_token")) ((com.fasterxml.jackson.databind.node.ObjectNode) user).set("refreshToken",data.get("refresh_token")); } establish(user,session,"oidc-user"); return safeReturnTo(returnTo); }
    public JsonNode gateway(HttpSession session, String path, String method, String body) { Object token=session.getAttribute("iamAccessToken"); if(token==null||token.toString().isBlank()) throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"当前会话没有 IAM Token"); if(path==null || !(path.startsWith("/api/v1/docs/") || path.startsWith("/api/v1/mdm/"))) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"仅允许代理文档中心和元数据中心接口"); return iam.proxy(path, method == null ? "GET" : method.toUpperCase(), token.toString(), body); }
    private Map<String,Object> establish(JsonNode root,HttpSession session,String account){ JsonNode data=root.path("data").isObject()?root.path("data"):root; String userId=data.path("userId").asText(data.path("sub").asText("")); if(userId.isBlank()) throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"IAM 未返回用户身份"); String role=properties.roleDefault().toUpperCase(); String accessToken=data.path("accessToken").asText(data.path("access_token").asText("")); String refreshToken=data.path("refreshToken").asText(data.path("refresh_token").asText("")); session.setAttribute("userId",userId); session.setAttribute("account",account); session.setAttribute("displayName",data.path("displayName").asText(data.path("name").asText(data.path("username").asText(account)))); session.setAttribute("role",role); session.setAttribute("orgId",data.path("orgId").asText("")); session.setAttribute("departmentId",data.path("departmentId").asText("")); session.setAttribute("iamAccessToken",accessToken); session.setAttribute("iamRefreshToken",refreshToken); session.setMaxInactiveInterval(8*60*60); return Map.of("userId",userId,"account",account,"displayName",session.getAttribute("displayName"),"role",role,"orgId",session.getAttribute("orgId"),"departmentId",session.getAttribute("departmentId"),"authSource","IAM"); }
    private String safeReturnTo(String value) { return java.util.Set.of("workspace", "ledger", "fulfillment", "base-config", "accounts").contains(value) ? value : "workspace"; }
}
